language: php

php:
  - 5.5.9
  - 5.5
  - 5.6

env:
  global:
    - setup=basic


sudo: false

script: phpunit --configuration phpunit.xml --coverage-clover=coverage.clover

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --access-token="9857f9bb4b1c260b94eb773a541d6e42e05db0db45d5a25757590276d5e50445" --format=php-clover coverage.clover
